- jesse/config.py
- jesse/enums/__init__.py
- jesse/modes/import_candles_mode/drivers/__init__.py
- jesse/modes/import_candles_mode/drivers/kraken.py
- jesse/services/project_maker/project_template/config.py
Following patterns of other exchanges, this commit adds support for
Kraken exchange.
> Adding support for Kraken exchange

- jesse/exceptions/__init__.py
- jesse/models/Exchange.py
- tests/test_exchange.py
Add check at `decrease_balance` or `increase_balance` it those make `self.balance` to be negative and throw exception if such occurrence happen
> add negative balance exception

- jesse/modes/optimize_mode/Genetics.py
- jesse/modes/optimize_mode/__init__.py
I let optimize mode overnight and woke up to see worse DNAs than when I left off. We should always keep the best DNA alive to prevent this from happening. Also, we should never keep more than 1 alive because that will kill the population diversity. I plan to make further improvements one by one in order to keep things under control and each change is evaluated individually.
> added elitism to genetic/evolution algorithm

- jesse/__init__.py
- jesse/modes/optimize_mode/Genetics.py
- jesse/modes/optimize_mode/__init__.py
Add support for csv and json snapshots.
> Optimize json csv

- jesse/services/file.py
Add the timeframes to the json export. The motivation of this change is to fix this issue there https://github.com/nicolay-zlobin/jesse-trades-info/issues/7
> export json add considering_timeframes

- jesse/strategies/Strategy.py
Ability to get completed trades inside strategy through `self.trades`.
> Ability to get completed trades inside strategy through self.trades

- jesse/models/Position.py
- tests/test_position.py
This seems like the fix for https://github.com/jesse-ai/jesse/issues/122
Also fixes a bug in the `mode` property of `Position`
> strategy.leverage instead of exchange.futures_leverage

- jesse/modes/optimize_mode/__init__.py
This typo somehow made it into the release
> Fix "sortino" ratio config string

- jesse/services/charts.py
Fixes jesse-ai/jesse#105 - unhandled exception when using --charts option and unc…losed (short?) position at end of backtest period.
> Fix issue #105 

- jesse/utils.py
> Typo in utils.py

- jesse/utils.py
- requirements.txt
- tests/test_utils.py
Adds denoising with wavelets to the utilities.
> Wavelet denoise

- jesse/services/db.py
> Pass database parameter to get rid of authentication issues

- jesse/services/db.py
Add new configrable env POSTGRES_SSLMODE
> Add new env POSTGRES_SSLMODE

- README.md
- codecov.yml
Added a badge for code coverage and a `codecov.yml` file for ignoring the `tests` directory.
> codecoverage file & badge

- jesse/indicators/__init__.py
- jesse/indicators/ha.py
- jesse/indicators/heikin_ashi_candles.py
- tests/test_indicators.py
Adding Heikin Ashi candles to be used as indicator on different strategies
> Heikin ashi candles

- jesse/services/installer.py
using os.remove instead of the explicit rm
> #361 os agnostic installer script

- jesse/strategies/Strategy.py
I added volume, timestamp, hl2, hlc3, hlcc4 and ohlc4 properties.
N.B timestamp returns an int, not sure if it should be a float.
> Extra properties to write simpler strategies

- jesse/services/logger.py
- jesse/services/notifier.py
- jesse/strategies/Strategy.py
2 Commits for:
* slack general & errors webhooks
* have a parameter for webhook. To create a customize channels for the strategy.
My team use slack as our main messaging app so we would really appreciate jesse to be compatible with slack.
Additionally, right now we have a lot of noise in our main discord channel for different symbols and different indicators.
My PR add the ability to create as many channels to use using a parameter in self.log()
> Slack notifier

- jesse/services/metrics.py
Adds DNA name to hyperparameters show div
> Add DNA name to stats

- jesse/models/FuturesExchange.py
Fix a prbolem that i made in my previous PR
https://github.com/jesse-ai/jesse/pull/430
the iteration on the list dont iterate the first item.
> fix(future-exchange): order cancellation

- README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Jesse Guru](https://gurubase.io/g/jesse) to Gurubase. Jesse Guru uses the data from this repo and data from the [docs](https://docs.jesse.trade/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Jesse Guru", which highlights that Jesse now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to …
> Introducing Jesse Guru on Gurubase.io

- jesse/constants.py
- jesse/enums/__init__.py
- jesse/helpers.py
- jesse/modes/backtest_mode.py
- tests/test_helpers.py
Refactored multiple small code snippets for improved performance and pythonic standards. Mainly targeting expensive or redundant operations.
Not meant to change any logic flow.
> Performance tweaks
