- jesse/services/charts.py
Fixes the Uncaught Exception: OSError: [Errno 22] Invalid argument: 'storage/charts/BT-2020-04-18T16:56:53.png'`
Windows doesn't like ":" in filenames.
> fix for --chart not working #5

- jesse/modes/import_candles_mode/__init__.py
Hey guys
I've just been playing around with Jesse today - trying to understand the workings of it etc. I was curious when I imported some candles from Binance how it said it would do three years of data in less than eight minutes - of course it didn't and took closer to 30. 
Just a tiny change - but I've switched the text on this prompt to say "minimum" instead of maximum - as the "time_to_finish" in this file assumes there is no time taken to load the data into the db between each request to the exchange. 
I'm looking to add some exchanges to this - so hopefully you'll see more of me in here with some more interesting PRs!
> Replace 'Maximum' with 'minimum' in candle import prompt

- jesse/indicators/supertrend.py
Supertrend indicator does not implement sequential mode correctly. This is apparent when working in a jupyter notebook, where sequential=True. Current indicator only outputs the last 240 values regardless of the number of candles passed. This should fix it.
> Fix sequential mode for supertrend

- jesse/indicators/bollinger_bands.py
- jesse/indicators/bollinger_bands_width.py
This PR parameterizes bollinger bands' upper and lower bands deviations, as well as the matype.
This will let people use custom values to help optimize strategies for instance, when building for a bear market to avoid buying too early.
> Parameterize bollinger bands upper, lower, and matype arguments

- jesse/modes/import_candles_mode/drivers/kraken.py
Kraken limits OHLC data to only the last 720 points at the given time
interval, for 1minute interval it means only last 12hours.
On the other hand, kraken provides full history of all the trades done
in the platform.
This commit changes the driver for importing candles, it exploit trades
history to create ohlc data at 1Min intervals.
Alright,
checked timestamps twice.
This is an example of lines in db
```
jesse_test_db=# select * from candle order by timestamp limit 3;
id                  |   timestamp   |  open  | close  |  high  |  low   |  volume  | symbol | exchange 
--------------------------------------+---------------+--------+--------+--------+--------+----------+--------+----------
f29d3454-02ff-4e71-a59a-a4aa6472409f | 1592006400000 | 8417.1 | 8417.1 | 8417.1 | 8417.1 |        0 …
```
> Kraken exchange: changing driver for candles import

- jesse/utils.py
- tests/test_strategy_utils.py
When converting candles into a dataframe, it would be nice to use pandas
datetime index rather than timestamp epoch.
This commit changes the utils function to convert epoch values to pandas
datetimes, tests are changed accordingly
> numpy_candles_to_dataframe: candles timestamp to pandas.Datetime

- jesse/__init__.py
When I ran the optimizer for the first time, I got `FileNotFoundError: [Errno 2] No such file or directory: '<path>/storage/logs/optimize.txt`. It was fixed by adding a `logs` folder, so I added a call to `os.makedirs` right before the handler would be attached.
> Ensure there's a log folder before attaching log handler

- jesse/helpers.py
- tests/test_helpers.py
In functions base_asset and quote_asset there are special if cases for
USDT and USD, this commit refactors the functions to accept easily any
other special cases like EUR GBP or BNB.
> Adding if cases for EUR in helpers functions

- jesse/helpers.py
While typed as `int`, the seconds parameter is often passed in as a float in reports, leading to outputs like this:
```python
readable_duration(184722.0, 3)
```
This is neither pretty nor correct, converting seconds to integer first always gives us the desired output:
```python
readable_duration(184722.0, 3)
```
> Only use integers in readable_duration output

- jesse/__init__.py
- jesse/modes/backtest_mode/__init__.py
- jesse/services/quantstats.py
- requirements.txt
The goal is to get quantstats' HTML report file using the [QuantStats](https://github.com/ranaroussi/quantstats) library after backtest ends.
[View original html file](https://rawcdn.githack.com/ranaroussi/quantstats/bd0e70bd284798a58c569363bc7e1c3c8c6e3fd9/docs/tearsheet.html). 
Example of use: 
`jesse backtest '2019-01-01' '2019-10-30' --full-reports`
> Ability to generate QuantStats' report

- jesse/strategies/Strategy.py
- jesse/strategies/__init__.py
This is my attempt at [**this task**](https://github.com/jesse-ai/jesse/projects/2#card-57833080)
The `cached` decorator can then be used like this:
```python
@property
@cached
def atr(self):
return atr(self.candles, self.vars['atr_period'])
```
However, when running the [**TurtleRules strategy**](https://github.com/jesse-ai/example-strategies/blob/master/TurtleRules/__init__.py), I had no noticeable performance gains. It may be that this strategy in particular is not that computationally expensive, though
I tried these three options and got more or less the same results:
```python
def cached(method):
def decorated(self, *args, **kwargs):
cached_method = self._cached_methods.get(method)
if cached_method is None:
cached_method = cache(method)
self._cached_methods[method] = cached_method …
```
> Cache expensive strategy methods

- Dockerfile
- DockerfileTest
- Switch to slim variant of the image
-> Reduces container image size from 1.5GB to 0.9GB (40% reduction)
- Updates Python to 3.9.4
> docker: Switch to slim image and update python version

- jesse/helpers.py
- tests/test_helpers.py
Motivation is to be able to inject env variables into the config where the key contains space like example: `env.exchanges.Binance Futures.settlement_currency`
> config key with space from env

- jesse/research/get_candles.py
This PR removes the titleization of the exchange name string in the function `get_candles` in research/get_candles.py and fixes `CandleNotFoundInDatabase` when using an exchange containing uppercases in its name, for ex the new 'FTX Futures'  exchange.
> removes exchange.title() transformation in research/get_candles.py

- jesse/services/env.py
- jesse/services/redis.py
As the title mention, this MR allow to use a redis database different than the default 0.
This can be usefull if using a redis instance outside of docker for example, or to be able to use multiple instances of jesse.
Code is backward compatible if the key is missing in the conf, `KeyError` are avoided by using `ENV_VALUES.get`.
> supports custom redis database number by passing REDIS_DB throught environment

- jesse/modes/import_candles_mode/__init__.py
bug fix: include all the arguments when recursively calling run in import_candles_mode.run
> Bug: original arguments not included in recursive call to run import_candles_mode.run

- jesse/modes/optimize_mode/fitness.py
It's been useful for me to log the DNA name in the optimization logs, just in case of failure or to test out specific values that for some reason may not make it through the optimization.
> Log the DNA name in the optimization log

- jesse/services/notifier.py
Telegram messages are sent using `Markdown` parser, yet most of markdown punctation is escaped here. 
To make notifications more useful, I disabled escaping, which enabled correct rendering for the following notificatiobs: 
```python
slf.log(f"{active}{slf.vars['bars']} {emoji}*{round(slf.position.pnl_percentage, 2)}%* [{slf.symbol}](https://www.binance.com/en/futures/{symbol}){slf.timeframe} *{order_kind}* dd: {round(slf.vars['drawdown'], 2)}%, ut: {round(slf.vars['uptick'], 2)}% {type(slf).__name__} {slf.port}: `{slf.note}`", send_notification=True)
```
Result:
> do not escape markdown punctuation

- jesse/services/broker.py
- jesse/strategies/Strategy.py
the math for calculation of percentage difference was wrong, resulting in MARKET orders instead of STOP/LIMIT for low-price asset pairs.
> fix percentage difference calculation math

- jesse/services/charts.py
Saleh,
I collate Jesse's backtest / walk forward results into a spreadsheet, and exsting equity curve was very faint when downscaling to fit into a cell. I somewhat improved it to be more readable, hope it's useful for others.
Changes:
- equity curve linewidth = 4, 
- added green/red fills for above / underwater periods
Before:
https://www.dropbox.com/s/ibp2owkbo8fikem/93308f1d-cbf9-43bf-aede-bba35f830997.png?dl=0
After:
https://www.dropbox.com/s/pgjipxr5lvy16v3/3e278f87-6b8d-4f95-9d73-fe5dde6e3d5e.png?dl=0
> improve equity curve readability

- jesse/services/metrics.py
- jesse/utils.py
I wanted to implement kelly criterion in my strategy after seeing this video:
https://www.youtube.com/watch?v=_FuuYSM7yOo&ab_channel=MarcinAnforowicz
Happy to know that jesse support that and also has an example in the docs.
https://docs.jesse.trade/docs/strategies/example-strategies.html#getting-the-size-right
Unfortunate after several experiments and investigatation I found that something is off. The problem was in the method of `utils.kelly_criterion`
The results are completly different between these formulas to `utils.kelly_criterion` formula.
> Kelly criterion calculated wrong.

- jesse/modes/optimize_mode/Optimize.py
This outputs a csv like so:
name: `STRATEGY-Binance Perpetual Futures-BTC-USDT-1h-2023-02-01-2023-10-01.csv`
```
iteration,dna,fitness,training_log.win-rate,training_log.total,training_log.PNL,testing_log.win-rate,testing_log.total,testing_log.PNL,parameters.param,parameters.param,parameters.param,parameters.param,parameters.param
32/500,/trah,0.8070215395981797,40,22,272.94,100,2,16.44,5,10,9,11,57
32/500,"8T,1u",0.7231400310451948,57,26,199.36,25,4,-21.89,11,6,1,3,68
32/500,";J,0p",0.7202389339032377,65,26,233.92,25,4,-21.89,13,5,1,3,64
32/500,3]mZ-,0.6792009839633323,50,20,218.9,100,2,16.44,8,7,9,10,7
32/500,/an.t,0.659519247874258,33,24,180.43,100,2,16.44,5,7,9,3,67
32/500,+aV>W,0.653210871623346,26,26,180.04,100,2,21.69,2,7,6,6,43 …
```
> Bring back logging, organize imports

- requirements.txt
I wanted to upgrade my python version from 3.9 to 3.11 and i was unable to install jesse  until i upgraded these packages. I  tried on 3.11.2 and 3.11.7 and on both of them the installation didnt work.
> Update requirements to 3.11.2

- jesse/models/FuturesExchange.py
I've notice that there are some strategies that works very fast and some very slow while they use the same indicators.
The difference was if i change the orders every candle.
The base code iterate over all of the orders from the beginning to the end while personally i dont know why its needed, beacuse most of the orders is always at the end. On my strategy it makes this loop iterate O(n**2) on the number of candles!
Simulation of 6 months, timeframe "5m"
Simply search from the end make a major difference for such strategies.
Base code:
173s
where on_order_cancel is 45s and getitem (again probably because of this loop) another 38s
With this change:
60s
> feat(FutureExchange): iterate the orders from the end makes the simulation run faster

- jesse/libs/dynamic_numpy_array/__init__.py
- jesse/modes/backtest_mode.py
- jesse/research/backtest.py
- jesse/store/state_candles.py
Now that I return to jesse, I want to try again this PR that makes jesse run faster by simply skip unused candles.
https://medium.com/@yakir4123/this-is-how-i-accelerated-jesse-a-python-framework-to-run-16-times-faster-part-i-4fce9c6ecef7
https://medium.com/@yakir4123/this-is-how-i-accelerated-jesse-a-python-framework-to-run-16-times-faster-part-ii-ec3a718095b3
I've tested it several times on different strategies.
Here is an example of timing the regular jesse algorithm for 2 years a strategy of route of 1h:
and with my algorithm:
* All the testes passed, the only thing that might be a problem that still I need to check is how well it works with several routes.
I think there may be a challange in there but that already can be used for optimization process where there is 1 route.
> Faster simulation

- jesse/strategies/Strategy.py
in case i want to cancel both of the exit orders without setting new exit orders I would like to do something like this:
```
self.stop_loss = []
self.take_profit = [] 
```
but it will raise an error of `'stop-loss and take-profit should not be exactly the same. Just use either one of them and it will do.'`
> fix(Strategy): cancel exit orders

- jesse/__init__.py
**What:** I've added the `APP_HOST` environment variable to make the host with which we [bind the uvicorn socket](https://www.uvicorn.org/settings/#socket-binding)  configurable.
**Why:** By default Jesse binds to `0.0.0.0:9000`, we can change the port by setting the `APP_PORT` to something different, but we cannot do that with the host. Using host `0.0.0.0` allows incoming traffic from any host to port `9000`. This has some undesirable side effects. 
A concrete example: Deploying Jesse with Docker in a DigitalOcean droplet, using Jesse's default socket, would expose the Jesse instance to the internet via the droplet's public IP on port 9000. Among other things, it makes the instance vulnerable to bruteforce attacks, if the attack suceeds, it would expose sensible data from the user. Also …
> Make app host configurable

- jesse/services/cache.py
Today out of the blue all my instances failed to restart with the following error:
```python
'  File "/home/ubuntu/jesse-bot/lib/python3.11/site-packages/jesse/services/cache.py", line 95, in <module>\n' +
'    cache = Cache("storage/temp/")\n' +
'            ^^^^^^^^^^^^^^^^^^^^^^\n' +
'  File "/home/ubuntu/jesse-bot/lib/python3.11/site-packages/jesse/services/cache.py", line 23, in __init__\n' +
'    self.db = pickle.load(f)\n' +
'              ^^^^^^^^^^^^^^\n' +
"UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 67: invalid start byte\n" +
'\n' +
```
Adding `UnicodeDecodeError` to handled exceptions helped.
> handle UnicodeDecodeError

- jesse/modes/backtest_mode.py
- jesse/strategies/Strategy.py
- jesse/strategies/TestCurrentRouteIndex1/__init__.py
- jesse/strategies/TestCurrentRouteIndex2/__init__.py
- tests/test_parent_strategy.py
- Old implementation has a O(n * m) time complexity.
- New implementation has a O(m * k).
- Where n = len(short_candles), m = len(orders), and k = average number of unmatched orders per step.
Tested locally across 5000+ trades, results are exactly the same as old implementation.
> Optimized _sort_execution_orders().

- jesse/helpers.py
from from is_pytest function to allow running backtesting with a pycharm runners
> 🔥 refactor(helpers): remove PyCharm test runner detection
